export const productFieldMap = {
  workspace_id: "workspaceId",
  input_source: "inputSource",
  source_url: "sourceUrl",
  image_url: "imageUrl",
  uploaded_image_url: "uploadedImageUrl",
  cost_price: "costPrice",
  margin_percent: "marginPercent",
  internal_code: "internalCode",
  supplier_name: "supplierName",
  supplier_contact: "supplierContact",
  supplier_lead_time_days: "supplierLeadTimeDays",
  stock_quantity: "stockQuantity",
  min_stock: "minStock",
  marketplace_origin: "marketplaceOrigin",
  product_url: "productUrl",
  affiliate_url: "affiliateUrl",
  analysis_summary: "analysisSummary",
  media_count: "mediaCount",
  posts_published: "postsPublished",
  videos_generated: "videosGenerated",
  created_at: "createdAt",
  created_date: "createdAt",
  updated_at: "updatedAt",
  updated_date: "updatedAt",
};

export const mediaAssetFieldMap = {
  workspace_id: "workspaceId",
  product_id: "productId",
  product_name: "productName",
  source_url: "sourceUrl",
  thumbnail_url: "thumbnailUrl",
  storage_key: "storageKey",
  mime_type: "mimeType",
  file_size: "fileSize",
  quality_score: "qualityScore",
  review_notes: "reviewNotes",
  reviewed_at: "reviewedAt",
  reviewed_by: "reviewedBy",
  previous_status: "previousStatus",
  rejection_reason: "rejectionReason",
  created_at: "createdAt",
  created_date: "createdAt",
  updated_at: "updatedAt",
  updated_date: "updatedAt",
};

export const postFieldMap = {
  workspace_id: "workspaceId",
  product_id: "productId",
  media_asset_id: "mediaAssetId",
  product_name: "productName",
  scheduled_at: "scheduledAt",
  published_at: "publishedAt",
  external_post_id: "externalPostId",
  external_url: "externalUrl",
  error_message: "errorMessage",
  engagement_likes: "engagementLikes",
  engagement_comments: "engagementComments",
  engagement_shares: "engagementShares",
  engagement_reach: "engagementReach",
  thumbnail_url: "thumbnailUrl",
  campaign_name: "campaignName",
  retry_count: "retryCount",
  last_sync_at: "lastSyncAt",
  created_at: "createdAt",
  created_date: "createdAt",
  updated_at: "updatedAt",
  updated_date: "updatedAt",
};

export const marketplaceListingFieldMap = {
  workspace_id: "workspaceId",
  product_id: "productId",
  stock_quantity: "stockQuantity",
  category_id: "categoryId",
  category_name: "categoryName",
  external_listing_id: "externalListingId",
  external_url: "externalUrl",
  error_message: "errorMessage",
  published_at: "publishedAt",
  last_sync_at: "lastSyncAt",
  created_at: "createdAt",
  created_date: "createdAt",
  updated_at: "updatedAt",
  updated_date: "updatedAt",
};

export const salesOrderFieldMap = {
  workspace_id: "workspaceId",
  customer_name: "customerName",
  customer_email: "customerEmail",
  cost_total: "costTotal",
  external_order_id: "externalOrderId",
  sold_at: "soldAt",
  created_at: "createdAt",
  created_date: "createdAt",
  updated_at: "updatedAt",
  updated_date: "updatedAt",
};

export const expenseFieldMap = {
  workspace_id: "workspaceId",
  spent_at: "spentAt",
  created_at: "createdAt",
  created_date: "createdAt",
  updated_at: "updatedAt",
  updated_date: "updatedAt",
};

export const commentFieldMap = {
  workspace_id: "workspaceId",
  post_id: "postId",
  external_comment_id: "externalCommentId",
  is_purchase_intent: "isPurchaseIntent",
  auto_replied: "autoReplied",
  reply_content: "replyContent",
  detected_at: "detectedAt",
  replied_at: "repliedAt",
  created_at: "createdAt",
  created_date: "createdAt",
  updated_at: "updatedAt",
  updated_date: "updatedAt",
};

export const jobFieldMap = {
  workspace_id: "workspaceId",
  product_id: "productId",
  media_asset_id: "mediaAssetId",
  post_id: "postId",
  result_url: "resultUrl",
  error_message: "errorMessage",
  created_at: "createdAt",
  created_date: "createdAt",
  updated_at: "updatedAt",
  updated_date: "updatedAt",
  completed_at: "completedAt",
};
