import { config } from "dotenv";
import { z } from "zod";

config({ path: ".env.local" });
config();

const envSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  PORT: z.coerce.number().default(3333),
  DATABASE_URL: z.string().default("postgresql://user:password@localhost:5432/automedia"),
  REDIS_URL: z.string().optional(),
  UPSTASH_REDIS_URL: z.string().optional(),
  UPSTASH_REDIS_REST_URL: z.string().optional(),
  UPSTASH_REDIS_REST_TOKEN: z.string().optional(),
  JWT_SECRET: z.string().min(16).default("change-me-in-production"),
  ENCRYPTION_KEY: z.string().optional(),
  ACCESS_TOKEN_TTL: z.string().default("15m"),
  REFRESH_TOKEN_TTL_DAYS: z.coerce.number().default(30),
  LOGIN_FAILURE_LIMIT: z.coerce.number().default(5),
  LOGIN_LOCK_MINUTES: z.coerce.number().default(15),
  LOGIN_WINDOW_MINUTES: z.coerce.number().default(15),
  WEBHOOK_SECRET: z.string().optional(),
  CORS_ORIGIN: z.string().default("https://auto-media-sooty.vercel.app,http://localhost:5173,http://localhost:4173"),
  FRONTEND_URL: z.string().url().default("https://auto-media-sooty.vercel.app"),
  API_PUBLIC_URL: z.string().url().default("https://auto-media-backend.vercel.app"),
  SOCIAL_INTEGRATIONS_MODE: z.enum(["mock", "live"]).default("mock"),
  META_CLIENT_ID: z.string().optional(),
  META_CLIENT_SECRET: z.string().optional(),
  META_REDIRECT_URI: z.string().url().optional(),
  META_GRAPH_VERSION: z.string().default("v21.0"),
  TIKTOK_CLIENT_KEY: z.string().optional(),
  TIKTOK_CLIENT_SECRET: z.string().optional(),
  TIKTOK_REDIRECT_URI: z.string().url().optional(),
  GOOGLE_CLIENT_ID: z.string().optional(),
  GOOGLE_CLIENT_SECRET: z.string().optional(),
  YOUTUBE_REDIRECT_URI: z.string().url().optional(),
  MERCADOLIVRE_CLIENT_ID: z.string().optional(),
  MERCADOLIVRE_CLIENT_SECRET: z.string().optional(),
  MERCADOLIVRE_REDIRECT_URI: z.string().url().optional(),
  SHOPEE_PARTNER_ID: z.string().optional(),
  SHOPEE_PARTNER_KEY: z.string().optional(),
  SHOPEE_REDIRECT_URI: z.string().url().optional(),
  SHOPEE_API_BASE_URL: z.string().url().default("https://partner.shopeemobile.com"),
  OPENAI_API_KEY: z.string().optional(),
  OPENAI_TEXT_MODEL: z.string().default("gpt-4.1-mini"),
  OPENAI_IMAGE_MODEL: z.string().default("gpt-image-1"),
  OPENAI_IMAGE_QUALITY: z.enum(["low", "medium", "high"]).default("high"),
  OPENAI_IMAGE_FALLBACK_ENABLED: z.enum(["true", "false"]).default("false").transform((value) => value === "true"),
  AI_VIDEO_PROVIDER: z.enum(["ffmpeg", "replicate_kling"]).default("ffmpeg"),
  AI_VIDEO_FALLBACK_TO_FFMPEG: z.enum(["true", "false"]).default("true").transform((value) => value === "true"),
  REPLICATE_API_TOKEN: z.string().optional(),
  REPLICATE_KLING_MODEL: z.string().default("kwaivgi/kling-v2.1"),
  REPLICATE_KLING_MODE: z.enum(["standard", "pro"]).default("standard"),
  REPLICATE_KLING_NEGATIVE_PROMPT: z.string().default("low quality, distorted product, unreadable text, extra fingers, deformed hands, watermark, logo distortion"),
  REPLICATE_POLL_INTERVAL_MS: z.coerce.number().default(5000),
  REPLICATE_TIMEOUT_MS: z.coerce.number().default(420000),
  STORAGE_DRIVER: z.enum(["local", "s3", "supabase"]).default("local"),
  UPLOADS_DIR: z.string().default("uploads"),
  S3_ENDPOINT: z.string().url().optional(),
  S3_PUBLIC_URL: z.string().url().optional(),
  S3_REGION: z.string().default("us-east-1"),
  S3_BUCKET: z.string().optional(),
  S3_ACCESS_KEY_ID: z.string().optional(),
  S3_SECRET_ACCESS_KEY: z.string().optional(),
  S3_FORCE_PATH_STYLE: z.enum(["true", "false"]).default("true").transform((value) => value === "true"),
  SUPABASE_URL: z.string().url().optional(),
  SUPABASE_SERVICE_ROLE_KEY: z.string().optional(),
  SUPABASE_STORAGE_BUCKET: z.string().default("videos"),
  VIDEO_RENDER_DRIVER: z.enum(["ffmpeg", "mock"]).default("ffmpeg"),
  FFMPEG_PATH: z.string().default("ffmpeg"),
});

export const env = envSchema.parse(process.env);
