import type { AutomationSettings, Comment, Job, MediaAsset, PlatformAccount, Post, Product } from "../types/domain.js";

export type CollectionName = "products" | "mediaAssets" | "posts" | "comments" | "jobs" | "platformAccounts";

type Database = {
  products: Product[];
  mediaAssets: MediaAsset[];
  posts: Post[];
  comments: Comment[];
  jobs: Job[];
  platformAccounts: PlatformAccount[];
  settings: AutomationSettings;
};

export const db: Database = {
  products: [
    {
      id: "prod_demo_smartwatch",
      name: "Smartwatch Pulse Pro",
      input_source: "manual",
      category: "Eletronicos",
      description: "Relogio inteligente com monitoramento cardiaco, notificacoes e bateria de longa duracao.",
      brand: "AutoMedia Test",
      price: 189.9,
      cost_price: 95,
      stock_quantity: 24,
      min_stock: 5,
      marketplace_origin: "Shopee",
      product_url: "https://example.com/smartwatch-pulse-pro",
      affiliate_url: "https://example.com/afiliado/smartwatch",
      keywords: ["smartwatch", "relogio inteligente", "fitness"],
      status: "draft",
      media_count: 1,
      posts_published: 0,
      videos_generated: 0,
      image_url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900",
      created_at: "2026-05-15T12:00:00.000Z",
      updated_at: "2026-05-15T12:00:00.000Z",
    },
    {
      id: "prod_demo_projector",
      name: "Mini Projetor CinemaGo",
      input_source: "manual",
      category: "Casa e Tecnologia",
      description: "Projetor portatil para filmes, aulas e apresentacoes com entrada HDMI e USB.",
      brand: "AutoMedia Test",
      price: 349.9,
      cost_price: 210,
      stock_quantity: 12,
      min_stock: 3,
      marketplace_origin: "Mercado Livre",
      product_url: "https://example.com/mini-projetor-cinemago",
      affiliate_url: "https://example.com/afiliado/projetor",
      keywords: ["projetor", "cinema em casa", "portatil"],
      status: "review",
      media_count: 2,
      posts_published: 0,
      videos_generated: 1,
      image_url: "https://images.unsplash.com/photo-1601944179066-29786cb9d32a?w=900",
      created_at: "2026-05-15T12:05:00.000Z",
      updated_at: "2026-05-15T12:05:00.000Z",
    },
    {
      id: "prod_demo_bottle",
      name: "Garrafa Termica HydraMax",
      input_source: "manual",
      category: "Lifestyle",
      description: "Garrafa termica inox com isolamento duplo para agua gelada ou quente.",
      brand: "AutoMedia Test",
      price: 79.9,
      cost_price: 35,
      stock_quantity: 48,
      min_stock: 8,
      marketplace_origin: "Shopee",
      product_url: "https://example.com/garrafa-hydramax",
      affiliate_url: "https://example.com/afiliado/hydramax",
      keywords: ["garrafa termica", "inox", "academia"],
      status: "approved",
      media_count: 1,
      posts_published: 1,
      videos_generated: 1,
      image_url: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=900",
      created_at: "2026-05-15T12:10:00.000Z",
      updated_at: "2026-05-15T12:10:00.000Z",
    },
    {
      id: "prod_demo_headphone",
      name: "Fone Bluetooth AirBeat",
      input_source: "manual",
      category: "Audio",
      description: "Fone sem fio com case carregador, microfone e cancelamento passivo de ruido.",
      brand: "AutoMedia Test",
      price: 129.9,
      cost_price: 62,
      stock_quantity: 30,
      min_stock: 6,
      marketplace_origin: "Mercado Livre",
      product_url: "https://example.com/fone-airbeat",
      affiliate_url: "https://example.com/afiliado/airbeat",
      keywords: ["fone bluetooth", "audio", "sem fio"],
      status: "draft",
      media_count: 1,
      posts_published: 0,
      videos_generated: 0,
      image_url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=900",
      created_at: "2026-05-15T12:15:00.000Z",
      updated_at: "2026-05-15T12:15:00.000Z",
    },
    {
      id: "prod_demo_lamp",
      name: "Luminaria LED Flex Desk",
      input_source: "manual",
      category: "Casa e Escritorio",
      description: "Luminaria articulada com tres tons de luz, dimmer e carregamento USB.",
      brand: "AutoMedia Test",
      price: 99.9,
      cost_price: 44,
      stock_quantity: 18,
      min_stock: 4,
      marketplace_origin: "Shopee",
      product_url: "https://example.com/luminaria-flex-desk",
      affiliate_url: "https://example.com/afiliado/luminaria",
      keywords: ["luminaria led", "home office", "mesa"],
      status: "scheduled",
      media_count: 1,
      posts_published: 0,
      videos_generated: 1,
      image_url: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=900",
      created_at: "2026-05-15T12:20:00.000Z",
      updated_at: "2026-05-15T12:20:00.000Z",
    },
    {
      id: "prod_demo_travelpack",
      name: "Kit Organizadores TravelPack",
      input_source: "manual",
      category: "Viagem",
      description: "Kit de necessaires e organizadores para mala, roupas e acessorios.",
      brand: "AutoMedia Test",
      price: 69.9,
      cost_price: 28,
      stock_quantity: 60,
      min_stock: 10,
      marketplace_origin: "Mercado Livre",
      product_url: "https://example.com/travelpack",
      affiliate_url: "https://example.com/afiliado/travelpack",
      keywords: ["organizador mala", "viagem", "necessaire"],
      status: "published",
      media_count: 1,
      posts_published: 2,
      videos_generated: 1,
      image_url: "https://images.unsplash.com/photo-1553531889-e6cf4d692b1b?w=900",
      created_at: "2026-05-15T12:25:00.000Z",
      updated_at: "2026-05-15T12:25:00.000Z",
    },
  ],
  mediaAssets: [
    {
      id: "asset_demo_smartwatch_image",
      product_id: "prod_demo_smartwatch",
      product_name: "Smartwatch Pulse Pro",
      type: "image",
      title: "Imagem principal - Smartwatch Pulse Pro",
      status: "collected",
      source: "seed-test",
      url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900",
      thumbnail_url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900",
      created_at: "2026-05-15T12:00:00.000Z",
      updated_at: "2026-05-15T12:00:00.000Z",
    },
    {
      id: "asset_demo_projector_video",
      product_id: "prod_demo_projector",
      product_name: "Mini Projetor CinemaGo",
      type: "generated_video",
      title: "Video produto - Mini Projetor CinemaGo",
      status: "pending_review",
      source: "IA Gerada",
      url: "https://images.unsplash.com/photo-1601944179066-29786cb9d32a?w=900",
      thumbnail_url: "https://images.unsplash.com/photo-1601944179066-29786cb9d32a?w=900",
      caption: "Transforme qualquer parede em cinema. Comente 'eu quero' para receber o link.",
      duration: "30s",
      created_at: "2026-05-15T12:05:00.000Z",
      updated_at: "2026-05-15T12:05:00.000Z",
    },
    {
      id: "asset_demo_bottle_video",
      product_id: "prod_demo_bottle",
      product_name: "Garrafa Termica HydraMax",
      type: "generated_video",
      title: "Video lifestyle - Garrafa Termica HydraMax",
      status: "approved",
      source: "IA Gerada",
      url: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=900",
      thumbnail_url: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=900",
      caption: "Agua gelada por horas, rotina mais pratica. Comente 'eu quero' para receber o link.",
      duration: "15s",
      platforms: ["instagram", "tiktok"],
      created_at: "2026-05-15T12:10:00.000Z",
      updated_at: "2026-05-15T12:10:00.000Z",
    },
    {
      id: "asset_demo_lamp_video",
      product_id: "prod_demo_lamp",
      product_name: "Luminaria LED Flex Desk",
      type: "generated_video",
      title: "Video review - Luminaria LED Flex Desk",
      status: "scheduled",
      source: "IA Gerada",
      url: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=900",
      thumbnail_url: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=900",
      caption: "Mais conforto para estudar, trabalhar e criar.",
      duration: "30s",
      platforms: ["instagram"],
      created_at: "2026-05-15T12:20:00.000Z",
      updated_at: "2026-05-15T12:20:00.000Z",
    },
  ],
  posts: [
    {
      id: "post_demo_bottle_instagram",
      product_id: "prod_demo_bottle",
      media_asset_id: "asset_demo_bottle_video",
      product_name: "Garrafa Termica HydraMax",
      platform: "instagram",
      caption: "Garrafa termica inox para manter sua rotina sempre no ponto. Comente eu quero para receber o link.",
      status: "published",
      published_at: "2026-05-15T13:00:00.000Z",
      thumbnail_url: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=900",
      engagement_likes: 132,
      engagement_comments: 18,
      engagement_shares: 9,
      engagement_reach: 2400,
      created_at: "2026-05-15T12:30:00.000Z",
      updated_at: "2026-05-15T13:00:00.000Z",
    },
    {
      id: "post_demo_lamp_schedule",
      product_id: "prod_demo_lamp",
      media_asset_id: "asset_demo_lamp_video",
      product_name: "Luminaria LED Flex Desk",
      platform: "instagram",
      caption: "Setup mais bonito, foco melhor e luz certa para cada momento.",
      status: "scheduled",
      scheduled_at: "2026-05-16T18:30:00.000Z",
      thumbnail_url: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=900",
      created_at: "2026-05-15T12:35:00.000Z",
      updated_at: "2026-05-15T12:35:00.000Z",
    },
  ],
  comments: [
    {
      id: "comment_demo_1",
      post_id: "post_demo_bottle_instagram",
      external_comment_id: "ig_comment_demo_1",
      author: "cliente_teste",
      content: "eu quero",
      platform: "instagram",
      is_purchase_intent: true,
      auto_replied: true,
      reply_content: "Claro! Aqui esta o link do produto: https://example.com/afiliado/hydramax",
      detected_at: "2026-05-15T13:10:00.000Z",
      replied_at: "2026-05-15T13:10:30.000Z",
    },
    {
      id: "comment_demo_2",
      post_id: "post_demo_bottle_instagram",
      external_comment_id: "ig_comment_demo_2",
      author: "comprador_curioso",
      content: "quanto custa?",
      platform: "instagram",
      is_purchase_intent: true,
      auto_replied: false,
      detected_at: "2026-05-15T13:20:00.000Z",
    },
  ],
  jobs: [
    {
      id: "job_demo_projector_video",
      type: "video_generation",
      status: "completed",
      title: "Gerar video product - Mini Projetor CinemaGo",
      progress: 100,
      product_id: "prod_demo_projector",
      media_asset_id: "asset_demo_projector_video",
      created_at: "2026-05-15T12:05:00.000Z",
      updated_at: "2026-05-15T12:08:00.000Z",
      completed_at: "2026-05-15T12:08:00.000Z",
    },
  ],
  platformAccounts: [
    { id: "platform_instagram", platform: "instagram", account_name: "Instagram", status: "disconnected" },
    { id: "platform_tiktok", platform: "tiktok", account_name: "TikTok", status: "disconnected" },
    { id: "platform_facebook", platform: "facebook", account_name: "Facebook", status: "disconnected" },
    { id: "platform_youtube", platform: "youtube", account_name: "YouTube", status: "disconnected" },
    { id: "platform_shopee", platform: "shopee", account_name: "Shopee", status: "disconnected" },
    { id: "platform_mercadolivre", platform: "mercadolivre", account_name: "Mercado Livre", status: "disconnected" },
  ],
  settings: {
    id: "automation_settings",
    auto_reply: true,
    auto_schedule: true,
    notifications: true,
    random_schedule: true,
    purchase_keywords: ["eu quero", "quanto custa", "como comprar", "onde comprar", "link do produto"],
    posting_start: "08:00",
    posting_end: "22:00",
    enabled_platforms: ["instagram", "tiktok", "facebook", "youtube", "shopee", "mercadolivre"],
  },
};

export function createId(prefix: string) {
  return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
}

export function nowIso() {
  return new Date().toISOString();
}

export function sortByDate<T extends { created_at?: string; updated_at?: string; published_at?: string; scheduled_at?: string }>(items: T[], order = "-created_at") {
  const desc = order.startsWith("-");
  const field = order.replace("-", "") as keyof T;

  return [...items].sort((first, second) => {
    const firstValue = String(first[field] || first.created_at || first.updated_at || "");
    const secondValue = String(second[field] || second.created_at || second.updated_at || "");
    return desc ? secondValue.localeCompare(firstValue) : firstValue.localeCompare(secondValue);
  });
}

export function applyLimit<T>(items: T[], limit?: number) {
  return typeof limit === "number" ? items.slice(0, limit) : items;
}

export function matchesFilter<T extends Record<string, unknown>>(item: T, filter: Partial<T>) {
  return Object.entries(filter).every(([key, value]) => value === undefined || item[key] === value);
}
